// src/data/doctorsData.js
export const HD1 =
  "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=800&q=80&auto=format&fit=crop";

export const INITIAL_DOCTORS = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialization: "Cardiologist",
    image: HD1,
    status: "available",
    available: true,
    experience: "12 years",
    qualifications: "MBBS, MD (Cardiology)",
    location: "City Hospital, Block A",
    about:
      "Expert in heart rhythm, cardiac care, and coronary interventions. Focused on patient-first care and minimally invasive procedures.",
    fee: 700,
    schedule: {
      "2025-02-18": ["09:00 AM", "10:00 AM", "11:30 AM", "12:30 PM"],
      "2025-02-19": ["02:00 PM", "03:30 PM", "05:00 PM"],
    },
    success: "98%",
    patients: "2k+",
    rating: 4.9,
  },
  {
    id: 2,
    name: "Dr. Ananya Singh",
    specialization: "Dermatologist",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=800&q=80&auto=format&fit=crop",
    status: "available",
    available: true,
    experience: "8 years",
    qualifications: "MBBS, DDV",
    location: "Skin Care Clinic, Floor 2",
    about:
      "Specialist in acne, psoriasis and cosmetic dermatology with a gentle approach.",
    fee: 500,
    schedule: {
      "2025-03-01": ["09:30 AM", "11:00 AM", "02:00 PM"],
    },
    success: "95%",
    patients: "1.5k+",
    rating: 4.7,
  },
  {
    id: 3,
    name: "Dr. Rajesh Kumar",
    specialization: "Orthopedic",
    image:
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80&auto=format&fit=crop",
    status: "away",
    available: false,
    experience: "15 years",
    qualifications: "MBBS, MS (Orthopedics)",
    location: "Orthocare Center, Wing B",
    about: "Hip and knee replacements, sports injuries and trauma care.",
    fee: 900,
    schedule: {
      "2025-03-05": ["11:00 AM", "02:30 PM"],
      "2025-03-07": ["09:00 AM", "12:00 PM", "03:00 PM"],
    },
    success: "92%",
    patients: "3k+",
    rating: 4.8,
  },
  {
    id: 4,
    name: "Dr. Meera Patel",
    specialization: "Pediatrician",
    image:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
    status: "available",
    available: true,
    experience: "10 years",
    qualifications: "MBBS, DCH",
    location: "Child Care Clinic, Ground Floor",
    about: "Child growth and immunization specialist, gentle with kids.",
    fee: 400,
    schedule: {
      "2025-03-03": ["09:00 AM", "10:30 AM", "04:00 PM"],
    },
    success: "99%",
    patients: "4k+",
    rating: 4.95,
  },
  {
    id: 5,
    name: "Dr. Meera Patel",
    specialization: "Pediatrician",
    image:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
    status: "available",
    available: false,
    experience: "10 years",
    qualifications: "MBBS, DCH",
    location: "Child Care Clinic, Ground Floor",
    about: "Child growth and immunization specialist, gentle with kids.",
    fee: 400,
    schedule: {
      "2025-03-03": ["09:00 AM", "10:30 AM", "04:00 PM"],
    },
    success: "99%",
    patients: "4k+",
    rating: 4.95,
  },
  {
    id: 6,
    name: "Dr. Meera Patel",
    specialization: "Pediatrician",
    image:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
    status: "available",
    available: false,
    experience: "10 years",
    qualifications: "MBBS, DCH",
    location: "Child Care Clinic, Ground Floor",
    about: "Child growth and immunization specialist, gentle with kids.",
    fee: 400,
    schedule: {
      "2025-03-03": ["09:00 AM", "10:30 AM", "04:00 PM"],
    },
    success: "99%",
    patients: "4k+",
    rating: 4.95,
  },
  {
    id: 7,
    name: "Dr. Meera Patel",
    specialization: "Pediatrician",
    image:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
    status: "available",
    available: true,
    experience: "10 years",
    qualifications: "MBBS, DCH",
    location: "Child Care Clinic, Ground Floor",
    about: "Child growth and immunization specialist, gentle with kids.",
    fee: 400,
    schedule: {
      "2025-03-03": ["09:00 AM", "10:30 AM", "04:00 PM"],
    },
    success: "99%",
    patients: "4k+",
    rating: 4.95,
  },
];
